# Generated by Django 2.2 on 2019-04-30 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190424_1407'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
